/**
 * Reference photos per species, sourced from Pexels and self-hosted under
 * public/species/. GENERATED by scripts/fetch-species-images.mjs — do not edit
 * by hand; re-run the script to refresh.
 *
 * Shown in the add-plant species picker so people can confirm they picked the
 * right plant by sight, not just an unfamiliar name. `author`/`sourceUrl` feed
 * the /credits page (the Pexels API asks for photographer + Pexels credit).
 */
export type SpeciesImage = {
  src: string;
  author: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
};

export const SPECIES_IMAGES: Record<string, SpeciesImage[]> = {
  "african-violet": [
    { src: "/species/african-violet-1.jpg", author: "Valentin Ivantsov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-african-violet-in-a-white-pot-36581193/" },
    { src: "/species/african-violet-2.jpg", author: "Anna Bondarenko", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-photo-of-flowers-7090475/" },
    { src: "/species/african-violet-3.jpg", author: "Andreas Schnabl", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-a-blue-blooming-african-violet-21365108/" },
  ],
  "air-plant-tillandsia": [
    { src: "/species/air-plant-tillandsia-1.jpg", author: "Valeria Palesska", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-a-plant-10194606/" },
    { src: "/species/air-plant-tillandsia-2.jpg", author: "Dmitry Kharitonov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/selective-focus-of-tillandsia-albida-20868772/" },
    { src: "/species/air-plant-tillandsia-3.jpg", author: "Valeria Palesska", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/houseplant-on-desk-10194603/" },
  ],
  "aloe": [
    { src: "/species/aloe-1.jpg", author: "Alexey Demidov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-a-black-pot-12448627/" },
    { src: "/species/aloe-2.jpg", author: "Lidia Bekenova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-close-up-shot-of-an-aloe-vera-plant-7408838/" },
    { src: "/species/aloe-3.jpg", author: "Fco Javier Carriola", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/leaves-of-aloes-19797887/" },
  ],
  "anthurium": [
    { src: "/species/anthurium-1.jpg", author: "Jef K", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-anthurium-flower-with-lush-greenery-30396852/" },
    { src: "/species/anthurium-2.jpg", author: "William ZALI", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-anthurium-plant-in-outdoor-garden-33559058/" },
    { src: "/species/anthurium-3.jpg", author: "Maria Tyutina", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/red-anthuriums-flowers-with-green-leaves-8458247/" },
  ],
  "areca-palm": [
    { src: "/species/areca-palm-1.jpg", author: "Yavuz Eren Güngör", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-small-plant-on-the-table-18063065/" },
    { src: "/species/areca-palm-2.jpg", author: "Alexey Demidov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/palm-plants-in-the-garden-12349129/" },
    { src: "/species/areca-palm-3.jpg", author: "Vova Kras", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leafed-plant-3126442/" },
  ],
  "bird-of-paradise": [
    { src: "/species/bird-of-paradise-1.jpg", author: "Jayakrishnan Krishnakumar", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/yellow-petaled-flower-2377186/" },
    { src: "/species/bird-of-paradise-2.jpg", author: "Alina Skazka", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/flowers-and-leaves-16647090/" },
    { src: "/species/bird-of-paradise-3.jpg", author: "Susanne Jutzeler, suju-foto", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-bird-of-paradise-17289905/" },
  ],
  "birds-nest-fern": [
    { src: "/species/birds-nest-fern-1.jpg", author: "hartono subagio", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-lush-green-fern-leaves-34191732/" },
    { src: "/species/birds-nest-fern-2.jpg", author: "Sunny Li", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-bird-s-nest-ferns-in-taiwan-garden-37484960/" },
    { src: "/species/birds-nest-fern-3.jpg", author: "Jeffry Surianto", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-bird-s-nest-fern-in-pot-close-up-37106452/" },
  ],
  "boston-fern": [
    { src: "/species/boston-fern-1.jpg", author: "Felipe Helfstein", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/boston-fern-leaves-16270192/" },
    { src: "/species/boston-fern-2.jpg", author: "Maya Ali", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-vibrant-green-ferns-in-sunlight-35987859/" },
    { src: "/species/boston-fern-3.jpg", author: "Joshua Mcknight", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-on-black-pot-3854749/" },
  ],
  "bromeliad": [
    { src: "/species/bromeliad-1.jpg", author: "Olli", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-red-bromeliad-plant-in-sunlight-37451410/" },
    { src: "/species/bromeliad-2.jpg", author: "Caique Gomes", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-red-bromeliad-flower-close-up-34705794/" },
    { src: "/species/bromeliad-3.jpg", author: "Zeynep KATIRCI", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-red-bromeliad-in-lush-green-foliage-37245253/" },
  ],
  "calathea": [
    { src: "/species/calathea-1.jpg", author: "MrGajowy3 Teodor", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-calathea-leaf-close-up-in-natural-setting-36483658/" },
    { src: "/species/calathea-2.jpg", author: "Edu Raw", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-green-potted-calathea-plant-leaves-37347934/" },
    { src: "/species/calathea-3.jpg", author: "Jardín  De Neko", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-calathea-orbifolia-houseplant-in-pot-33448610/" },
  ],
  "cast-iron-plant": [
    { src: "/species/cast-iron-plant-1.jpg", author: "Alina Gribanova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leaves-with-lines-in-close-up-6484637/" },
    { src: "/species/cast-iron-plant-2.jpg", author: "Ala J Graczyk", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-plant-outside-in-front-of-a-painted-window-16710149/" },
    { src: "/species/cast-iron-plant-3.jpg", author: "Jose Rodriguez Ortega", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-green-aspidistra-plant-in-urban-alleyway-38162473/" },
  ],
  "chinese-evergreen": [
    { src: "/species/chinese-evergreen-1.jpg", author: "K", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leafed-plant-3119964/" },
    { src: "/species/chinese-evergreen-2.jpg", author: "EL The Explorer", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-an-aglaonema-plant-12243538/" },
    { src: "/species/chinese-evergreen-3.jpg", author: "Kulbir", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-person-holding-the-plant-of-chinese-evergreen-9311882/" },
  ],
  "chinese-money-plant": [
    { src: "/species/chinese-money-plant-1.jpg", author: "Kulbir", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-a-green-plant-7180559/" },
    { src: "/species/chinese-money-plant-2.jpg", author: "Kulbir", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-white-ceramic-pot-7210780/" },
    { src: "/species/chinese-money-plant-3.jpg", author: "Kulbir", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/pilea-peperomioides-plant-in-white-ceramic-pot-6853078/" },
  ],
  "christmas-cactus": [
    { src: "/species/christmas-cactus-1.jpg", author: "Sergej  *****", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-christmas-cactus-in-rustic-pot-34880906/" },
    { src: "/species/christmas-cactus-2.jpg", author: "Dmitry Kharitonov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-schlumbergera-plant-in-bloom-20137809/" },
    { src: "/species/christmas-cactus-3.jpg", author: "Ramon Perucho", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-a-bright-pink-flower-19602362/" },
  ],
  "croton": [
    { src: "/species/croton-1.jpg", author: "compack disc", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-croton-leaves-in-natural-light-36684052/" },
    { src: "/species/croton-2.jpg", author: "aksinfo7 universe", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/beautiful-variegated-croton-leaves-in-sunlight-36893931/" },
    { src: "/species/croton-3.jpg", author: "Erik Mclean", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/selective-focus-of-croton-plants-11457407/" },
  ],
  "dieffenbachia": [
    { src: "/species/dieffenbachia-1.jpg", author: "Mobile Photography®", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-green-leaves-7439365/" },
    { src: "/species/dieffenbachia-2.jpg", author: "Nandda Souza", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-dieffenbachia-plant-leaves-30800552/" },
    { src: "/species/dieffenbachia-3.jpg", author: "Alexey Demidov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/dieffenbachia-seguine-plant-10482140/" },
  ],
  "dracaena-marginata": [
    { src: "/species/dracaena-marginata-1.jpg", author: "Maryann Kariuki", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/exotic-green-potted-houseplant-on-white-surface-4299019/" },
    { src: "/species/dracaena-marginata-2.jpg", author: "Yeşim Çolak", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/sunlit-indoor-plant-casting-shadows-on-wall-31024989/" },
    { src: "/species/dracaena-marginata-3.jpg", author: "Sid Maia", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-on-white-wall-3489128/" },
  ],
  "echeveria": [
    { src: "/species/echeveria-1.jpg", author: "fei wang", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-succulent-plants-14245929/" },
    { src: "/species/echeveria-2.jpg", author: "Duc Anh Nguyen", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-succulent-plant-8147056/" },
    { src: "/species/echeveria-3.jpg", author: "Lara Farber", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-green-succulents-7607544/" },
  ],
  "english-ivy": [
    { src: "/species/english-ivy-1.jpg", author: "Greta Hoffman", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plants-in-pots-on-farm-7728872/" },
    { src: "/species/english-ivy-2.jpg", author: "Eriks Abzinovs", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leaves-3117228/" },
    { src: "/species/english-ivy-3.jpg", author: "Arina Krasnikova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-leaves-6317496/" },
  ],
  "fiddle-leaf-fig": [
    { src: "/species/fiddle-leaf-fig-1.jpg", author: "Lachlan  Ross", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-ficus-lyrata-on-table-7084309/" },
    { src: "/species/fiddle-leaf-fig-2.jpg", author: "Lachlan  Ross", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-potted-plant-with-fresh-leaves-7084324/" },
    { src: "/species/fiddle-leaf-fig-3.jpg", author: "Orione  Conceição", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-person-holding-a-potted-ficus-lyrata-15191694/" },
  ],
  "haworthia": [
    { src: "/species/haworthia-1.jpg", author: "Sandeep Singh", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/succulent-in-a-square-pot-5856066/" },
    { src: "/species/haworthia-2.jpg", author: "Anca", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-white-ceramic-pot-7118700/" },
    { src: "/species/haworthia-3.jpg", author: "Jessica Lewis 🦋 thepaintedsquare", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-photograph-of-white-and-green-leaves-10880506/" },
  ],
  "heartleaf-philodendron": [
    { src: "/species/heartleaf-philodendron-1.jpg", author: "Ahmad Fauzi Al Faridi", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-green-philodendron-leaves-closeup-36582295/" },
    { src: "/species/heartleaf-philodendron-2.jpg", author: "Sasha  Kim", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/person-holding-a-hanging-plant-9413775/" },
    { src: "/species/heartleaf-philodendron-3.jpg", author: "Joshua Mcknight", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/heartleaf-philodendron-plant-on-pots-3854750/" },
  ],
  "hoya-wax-plant": [
    { src: "/species/hoya-wax-plant-1.jpg", author: "Felipe Alves", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leaves-of-plant-in-white-ceramic-pot-9297353/" },
    { src: "/species/hoya-wax-plant-2.jpg", author: "Gene&Mandee Maroulitsas", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-delicate-hoya-carnosa-flowers-35060566/" },
    { src: "/species/hoya-wax-plant-3.jpg", author: "Gene&Mandee Maroulitsas", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/delicate-hoya-carnosa-flower-in-soft-focus-35060562/" },
  ],
  "jade-plant": [
    { src: "/species/jade-plant-1.jpg", author: "Febe Theodora", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/two-plants-in-pots-1836600/" },
    { src: "/species/jade-plant-2.jpg", author: "Mario Spencer", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-a-green-crassula-ovata-succulent-plant-36346257/" },
    { src: "/species/jade-plant-3.jpg", author: "Bruchin Noeka", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/succulent-plant-in-a-garden-6011343/" },
  ],
  "kalanchoe": [
    { src: "/species/kalanchoe-1.jpg", author: "Du Tử Mộng", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/blooming-orange-flowers-in-brown-pot-2333906/" },
    { src: "/species/kalanchoe-2.jpg", author: "Guzel Sadykova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/colorful-kalanchoe-blossfeldiana-bouquets-33024685/" },
    { src: "/species/kalanchoe-3.jpg", author: "Jessika Arraes", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-green-plant-7763838/" },
  ],
  "lucky-bamboo": [
    { src: "/species/lucky-bamboo-1.jpg", author: "Markus Winkler", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/clusters-of-lucky-bamboo-plants-13677856/" },
    { src: "/species/lucky-bamboo-2.jpg", author: "Lidia Bekenova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-bamboo-with-green-leaves-7352303/" },
    { src: "/species/lucky-bamboo-3.jpg", author: "Hafize  Balcı", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/elegant-lucky-bamboo-plant-in-glass-vase-30384232/" },
  ],
  "maidenhair-fern": [
    { src: "/species/maidenhair-fern-1.jpg", author: "豫 庞", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-vibrant-green-fern-leaves-with-water-droplets-34046762/" },
    { src: "/species/maidenhair-fern-2.jpg", author: "Muhammad Hendrawan, S. Pd", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-green-maidenhair-fern-foliage-close-up-35522425/" },
    { src: "/species/maidenhair-fern-3.jpg", author: "Bui Van Dong", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-green-leave-18133929/" },
  ],
  "majesty-palm": [
    { src: "/species/majesty-palm-1.jpg", author: "Maksim Goncharenok", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-green-plant-with-leaves-4596808/" },
    { src: "/species/majesty-palm-2.jpg", author: "David Munoz", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-green-tropical-palm-leaves-close-up-33421594/" },
    { src: "/species/majesty-palm-3.jpg", author: "Jess Loiterton", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/areca-plants-growing-in-a-garden-4327640/" },
  ],
  "money-tree": [
    { src: "/species/money-tree-1.jpg", author: "Daan Rink", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-plant-beside-the-window-7047366/" },
    { src: "/species/money-tree-2.jpg", author: "Loft of SAX", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-the-leaves-of-a-potted-plant-15039491/" },
    { src: "/species/money-tree-3.jpg", author: "Kha Ruxury", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/money-tree-houseplant-and-a-glass-jug-on-a-dresser-17151138/" },
  ],
  "monstera": [
    { src: "/species/monstera-1.jpg", author: "Anca", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-monstera-deliciosa-green-plant-7318283/" },
    { src: "/species/monstera-2.jpg", author: "Dani Randall", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/big-green-monstera-leaf-17619301/" },
    { src: "/species/monstera-3.jpg", author: "Esra Afşar", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-monstera-leaf-in-natural-sunlight-36477236/" },
  ],
  "monstera-adansonii": [
    { src: "/species/monstera-adansonii-1.jpg", author: "Jardín  De Neko", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-swiss-cheese-plant-monstera-indoors-32286095/" },
    { src: "/species/monstera-adansonii-2.jpg", author: "Talha Kuğu", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-monstera-leaves-with-intricate-patterns-37118223/" },
    { src: "/species/monstera-adansonii-3.jpg", author: "hello aesthe", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-close-up-of-a-plant-with-green-leaves-27400958/" },
  ],
  "nerve-plant": [
    { src: "/species/nerve-plant-1.jpg", author: "Melbin Jacob", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-fittonia-foliage-with-veined-leaves-38542809/" },
    { src: "/species/nerve-plant-2.jpg", author: "Egor Komarov", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-photo-of-leaves-11692283/" },
    { src: "/species/nerve-plant-3.jpg", author: "Kenny", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-potted-nerve-plants-12351052/" },
  ],
  "norfolk-island-pine": [
    { src: "/species/norfolk-island-pine-1.jpg", author: "Tim & Martin Klement", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/majestic-norfolk-pines-in-hawaiian-landscape-30664944/" },
    { src: "/species/norfolk-island-pine-2.jpg", author: "Dario Durham", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/beautiful-norfolk-island-pine-against-blue-sky-33578798/" },
    { src: "/species/norfolk-island-pine-3.jpg", author: "Rajesh S  Balouria", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-an-australian-pine-branch-15684435/" },
  ],
  "parlor-palm": [
    { src: "/species/parlor-palm-1.jpg", author: "Sóc Năng Động", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/small-potted-palm-on-wooden-table-37188193/" },
    { src: "/species/parlor-palm-2.jpg", author: "Engin Akyurt", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-bright-green-leaves-of-neanthe-bella-palms-16689889/" },
    { src: "/species/parlor-palm-3.jpg", author: "Cintia  Cerpa", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-palms-leaves-in-close-up-photography-11210268/" },
  ],
  "peace-lily": [
    { src: "/species/peace-lily-1.jpg", author: "www.kaboompics.com", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/person-holding-plant-in-a-pot-4751967/" },
    { src: "/species/peace-lily-2.jpg", author: "Subhrajyoti Paul", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-white-peace-lily-in-garden-setting-32425127/" },
    { src: "/species/peace-lily-3.jpg", author: "cottonbro studio", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plants-in-brown-clay-pots-9731992/" },
  ],
  "phalaenopsis-orchid": [
    { src: "/species/phalaenopsis-orchid-1.jpg", author: "Emel Cirakoglu", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/white-flowers-on-gray-background-18378607/" },
    { src: "/species/phalaenopsis-orchid-2.jpg", author: "Andréa Devillier", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/elegant-white-orchids-against-warm-background-35531494/" },
    { src: "/species/phalaenopsis-orchid-3.jpg", author: "Rachella Roepa", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-yellow-orchids-against-a-clean-background-34216936/" },
  ],
  "philodendron-birkin": [
    { src: "/species/philodendron-birkin-1.jpg", author: "Drew Dempsey", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-indoor-garden-with-diverse-potted-plants-28753971/" },
    { src: "/species/philodendron-birkin-2.jpg", author: "Tara Winstead", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-potted-philodendron-birkins-beside-a-glass-window-7663987/" },
    { src: "/species/philodendron-birkin-3.jpg", author: "Katarzyna Modrzejewska", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-close-up-photography-7494831/" },
  ],
  "polka-dot-plant": [
    { src: "/species/polka-dot-plant-1.jpg", author: "Anina Güntensperger", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-pink-leaves-10999665/" },
    { src: "/species/polka-dot-plant-2.jpg", author: "TU HAN-WEI", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-polka-dot-plants-in-red-and-green-35360013/" },
    { src: "/species/polka-dot-plant-3.jpg", author: "Victor Candiani", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/pink-and-green-leaves-in-macro-photography-6134816/" },
  ],
  "ponytail-palm": [
    { src: "/species/ponytail-palm-1.jpg", author: "T. Royce Xan", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-plant-with-leaves-10785988/" },
    { src: "/species/ponytail-palm-2.jpg", author: "Kriss  L", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-ponytail-palm-in-sunlit-patio-setting-30343680/" },
    { src: "/species/ponytail-palm-3.jpg", author: "Ivan S", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-brown-pot-7212859/" },
  ],
  "pothos": [
    { src: "/species/pothos-1.jpg", author: "Ja Kubislav", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/plants-in-flowerpots-14534666/" },
    { src: "/species/pothos-2.jpg", author: "Teona Swift", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-plant-with-green-leaves-6913641/" },
    { src: "/species/pothos-3.jpg", author: "Nataliya Vaitkevich", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leaves-beside-white-wall-4641442/" },
  ],
  "prayer-plant": [
    { src: "/species/prayer-plant-1.jpg", author: "www.kaboompics.com", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-photo-of-green-plant-4590442/" },
    { src: "/species/prayer-plant-2.jpg", author: "Matheus Bertelli", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-leaves-on-a-shrub-20233792/" },
    { src: "/species/prayer-plant-3.jpg", author: "Saleh Almawed", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-prayer-plant-leaves-display-32980736/" },
  ],
  "rex-begonia": [
    { src: "/species/rex-begonia-1.jpg", author: "Leonard Richards", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-red-begonia-leaves-in-nature-34312913/" },
    { src: "/species/rex-begonia-2.jpg", author: "Jeffry Surianto", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-of-spiral-begonia-leaf-pattern-36775907/" },
    { src: "/species/rex-begonia-3.jpg", author: "Matheus Bertelli", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/leaves-on-a-shrub-in-forest-20233824/" },
  ],
  "rubber-plant": [
    { src: "/species/rubber-plant-1.jpg", author: "Hanna Pad", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-on-brown-pot-8989427/" },
    { src: "/species/rubber-plant-2.jpg", author: "Scott Webb", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/monochrome-photo-of-rubber-plant-1903964/" },
    { src: "/species/rubber-plant-3.jpg", author: "Arthur  Uzoagba", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/rubber-plant-in-green-pot-on-brick-wall-indoors-29518481/" },
  ],
  "schefflera": [
    { src: "/species/schefflera-1.jpg", author: "Артем Смолдарев", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-green-plant-7462741/" },
    { src: "/species/schefflera-2.jpg", author: "Ryszard Zaleski", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/sunlight-behind-plant-leaves-15497753/" },
    { src: "/species/schefflera-3.jpg", author: "Teona Swift", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/bush-with-fresh-green-leaves-in-sunlight-6913604/" },
  ],
  "snake-plant": [
    { src: "/species/snake-plant-1.jpg", author: "Mustafa Akın", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/stylish-indoor-snake-plant-in-modern-pot-29218657/" },
    { src: "/species/snake-plant-2.jpg", author: "Nadiye Odabaşı", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/potted-plants-at-home-10467813/" },
    { src: "/species/snake-plant-3.jpg", author: "Olha Ruskykh", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-sansevieria-plant-leaves-in-light-room-6279940/" },
  ],
  "spider-plant": [
    { src: "/species/spider-plant-1.jpg", author: "Celal Metin", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-indoor-spider-plant-on-wooden-table-31757820/" },
    { src: "/species/spider-plant-2.jpg", author: "Natalia Sevruk", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/lush-green-spider-plants-on-stone-wall-36314009/" },
    { src: "/species/spider-plant-3.jpg", author: "PARTY MALL", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/cozy-indoor-garden-with-spider-plant-and-rustic-decor-34681349/" },
  ],
  "string-of-hearts": [
    { src: "/species/string-of-hearts-1.jpg", author: "Bruno Abdiel", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-green-leaves-on-wicker-basket-10592221/" },
    { src: "/species/string-of-hearts-2.jpg", author: "Lisett Kruusimäe", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/heart-cutouts-on-a-white-wall-13786304/" },
    { src: "/species/string-of-hearts-3.jpg", author: "Nichita  Grimovici", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-hanging-potted-plant-13593070/" },
  ],
  "string-of-pearls": [
    { src: "/species/string-of-pearls-1.jpg", author: "Rumeysa Akbaş", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/string-of-pearls-in-a-pot-13799658/" },
    { src: "/species/string-of-pearls-2.jpg", author: "Ant Armada", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-buds-hanging-on-branches-20601177/" },
    { src: "/species/string-of-pearls-3.jpg", author: "Rumeysa Akbaş", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/close-up-shot-of-a-plant-13799752/" },
  ],
  "tradescantia-inch-plant": [
    { src: "/species/tradescantia-inch-plant-1.jpg", author: "Anna Khomutova", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/a-plant-in-a-box-5783142/" },
    { src: "/species/tradescantia-inch-plant-2.jpg", author: "Nothing Ahead", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/vibrant-tradescantia-zebrina-foliage-background-32795767/" },
    { src: "/species/tradescantia-inch-plant-3.jpg", author: "İrem  Akkoyun", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/plant-on-shelf-17115891/" },
  ],
  "zz-plant": [
    { src: "/species/zz-plant-1.jpg", author: "cottonbro studio", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-on-white-ceramic-pot-4503744/" },
    { src: "/species/zz-plant-2.jpg", author: "Ksenia Chernaya", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-zamioculcas-on-white-pot-3952024/" },
    { src: "/species/zz-plant-3.jpg", author: "Polina Zimmerman", license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", sourceUrl: "https://www.pexels.com/photo/green-plant-in-white-ceramic-pot-3747079/" },
  ],
};
